# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUdmInSExg8F-_Pyv4m1eVFO06tT8EHF
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing import image
# import numpy as np
# from PIL import Image
# import os
# import io
# 
# # --- Configuration ---
# # CRITICAL: This path must match the model file you upload to GitHub
# MODEL_PATH = 'brain_tumor_detection_mobilenetv2.h5'
# IMAGE_SIZE = (224, 224)
# CLASS_NAMES = ['No Tumor', 'Tumor']
# # ---------------------
# 
# # --- Helper Function to Load the Model ---
# # @st.cache_resource ensures the model is loaded only once for better performance
# @st.cache_resource
# def load_classification_model():
#     """Loads the pre-trained Keras model and caches it."""
#     if not os.path.exists(MODEL_PATH):
#         st.error(f"Error: Model file not found at '{MODEL_PATH}'. Please ensure it's committed to your GitHub repository.")
#         return None
#     try:
#         model = load_model(MODEL_PATH)
#         return model
#     except Exception as e:
#         st.error(f"Failed to load the model: {e}")
#         return None
# 
# # --- Helper Function for Prediction ---
# def preprocess_and_predict(uploaded_file, model):
#     """Preprocesses the image from the uploaded file object and makes a prediction."""
# 
#     # Read the file contents into a PIL Image object
#     img = Image.open(uploaded_file).convert('RGB')
# 
#     # 1. Resize Image
#     img = img.resize(IMAGE_SIZE)
# 
#     # 2. Convert to Array and Normalize (must match training)
#     img_array = image.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0)
#     img_array = img_array / 255.0
# 
#     # 3. Predict
#     prediction = model.predict(img_array)
#     probability = prediction[0][0]
# 
#     # Determine the predicted class (0 or 1)
#     predicted_class_index = int(np.round(probability))
#     predicted_class = CLASS_NAMES[predicted_class_index]
# 
#     # Format the confidence percentage
#     confidence = probability if predicted_class_index == 1 else (1 - probability)
# 
#     return predicted_class, confidence * 100
# 
# # --- Streamlit App Interface ---
# 
# # a) Page Title
# st.set_page_config(page_title="Brain Tumor Detection System", layout="centered")
# st.title("🧠 Brain Tumor Detection System (AI Powered)")
# st.caption("Using Transfer Learning (MobileNetV2) and Streamlit")
# 
# # Load the model only once
# model = load_classification_model()
# 
# if model is None:
#     st.stop()
# 
# st.markdown("---")
# 
# # b) Image Upload Section
# uploaded_file = st.file_uploader(
#     "Upload a Brain MRI Image (JPG or PNG)",
#     type=["jpg", "jpeg", "png"]
# )
# 
# if uploaded_file is not None:
#     # Display image preview
#     st.image(Image.open(uploaded_file), caption="Uploaded MRI Image", use_column_width=True)
# 
#     st.markdown("---")
# 
#     # c) Prediction Button
#     if st.button("Detect Tumor", type="primary"):
#         with st.spinner('Analyzing MRI image...'):
#             # Rewind file pointer and predict
#             uploaded_file.seek(0)
#             predicted_class, confidence = preprocess_and_predict(uploaded_file, model)
# 
#             # d) Output Section
#             st.subheader("📊 Analysis Result")
# 
#             # Display result with color coding
#             if predicted_class == 'Tumor':
#                 st.error(f"Prediction: *{predicted_class}*")
#                 st.balloons()
#             else:
#                 st.success(f"Prediction: *{predicted_class}*")
# 
#             st.metric(label="Confidence Level", value=f"{confidence:.2f} %")
# 
#             st.markdown(
#                 """
#                 > *Disclaimer:* This system is for educational and demonstrative purposes only.
#                 > Consult a qualified medical professional for any diagnostic decisions.
#                 """
#             )
# else:
#     st.info("Awaiting MRI image upload...")
# 
# st.markdown("---")
# st.write("Project built for Deep Learning/CNN Assignment.")

